<?php

namespace Database\Seeders;

use App\Models\Frontend\ActivityLog;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ActivityLogSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = array(
            0 =>
            array(
                'id' => '1d16bb752d6047649360',
                'user_id' => 'admin',
                'description' => 'Transactions status is approve by admin',
                'created_at' => '2023-06-23T13:51:33+00:00',
                'title' => 'Status approve',
            ),
            1 =>
            array(
                'id' => '21e42241470e4bc8901d',
                'user_id' => 'admin',
                'description' => 'Transactions status is approve by admin',
                'created_at' => '2023-06-23T13:53:49+00:00',
                'title' => 'Status approve',
            ),
            2 =>
            array(
                'id' => '36d403dc562241c0bea4',
                'user_id' => 'admin',
                'description' => '1000 eMoney is Generated by admin at ',
                'created_at' => 1687528142000,
                'title' => 'eMoney is Generated',
            ),
            3 =>
            array(
                'id' => '3bc8736e0ecc41649d5e',
                'user_id' => 'admin',
                'description' => '1000 eMoney is Generated by admin at ',
                'created_at' => 1687527951000,
                'title' => 'eMoney is Generated',
            ),
            4 =>
            array(
                'id' => '533ca4caf3e843279c3f',
                'user_id' => 'admin',
                'description' => 'Transactions status is approve by admin',
                'title' => 'Status approve',
                'created_at' =>
                array(
                    '_seconds' => 1686651884,
                    '_nanoseconds' => 766000000,
                ),
            ),
            5 =>
            array(
                'id' => '622995bf34424cbebe55',
                'user_id' => 'admin',
                'description' => '100eMoney is Generated by admin',
                'created_at' => 1686650948000,
                'title' => 'eMoney is Generated',
            ),
            6 =>
            array(
                'id' => '625390dc8a094c6ca4c4',
                'user_id' => 'admin',
                'description' => '100 eMoney is Generated by admin at ',
                'created_at' => 1687519237000,
                'title' => 'eMoney is Generated',
            ),
            7 =>
            array(
                'id' => '8729d4c4e9c14d8e9ccf',
                'user_id' => 'admin',
                'description' => '1000 eMoney is Generated by admin at ',
                'created_at' => 1687531124000,
                'title' => 'eMoney is Generated',
            ),
            8 =>
            array(
                'id' => '9b58bdc3706c42c6b6f3',
                'user_id' => 'admin',
                'description' => '1000 eMoney is Generated by admin at ',
                'created_at' => 1687531373000,
                'title' => 'eMoney is Generated',
            ),
            9 =>
            array(
                'id' => 'b6d1160862474d3c9c65',
                'user_id' => 'admin',
                'description' => 'Transactions status is approve by admin',
                'created_at' => '2023-06-13T10:27:42+00:00',
                'title' => 'Status approve',
            ),
            10 =>
            array(
                'id' => 'ctAJQIrQf1oMnmTk1nOn',
                'created_at' =>
                array(
                    '_seconds' => 1686649420,
                    '_nanoseconds' => 526000000,
                ),
                'description' => 'Admin Generated eMoney',
                'title' => 'Generate eMoney',
                'user_id' => '2HPLE2GZMJartR7jaNCuD1KDfbz2',
            ),
            11 =>
            array(
                'id' => 'pX3TAvh3pbWqakBmCVPb',
                'user_id' => '0C5vtMYV6UaoCpR4i54FDuoUVDk1',
                'created_at' =>
                array(
                    '_seconds' => 1686650474,
                    '_nanoseconds' => 615000000,
                ),
                'description' => 'User request for eMoney',
                'title' => 'Request For eMoney',
            ),
        );

        DB::table('activity_logs')->truncate();
        foreach ($data as $item) {

            $user = User::where('uid', $item['user_id'])->first();
            ActivityLog::create([
                'user_id' => $user?->id ?? null,
                'uid' => $item['id'],
                'title' => $item['title'],
                'description' => $item['description'],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]);
        }
    }
}
