<?php

namespace Database\Seeders;

use App\Models\Advertisement;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class AdvertisementSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $startDate = Carbon::now();
        $endDate = Carbon::now()->addDays(30);

        // Sample online URLs for images and videos
        $restaurantImages = [
            'https://linkup-vibe.s3.eu-central-1.amazonaws.com/ads/restaurant1.jpg',
            'https://linkup-vibe.s3.eu-central-1.amazonaws.com/ads/restaurant2.jpg',
            'https://linkup-vibe.s3.eu-central-1.amazonaws.com/ads/restaurant3.jpg',
            'https://linkup-vibe.s3.eu-central-1.amazonaws.com/ads/restaurant4.jpg',
            'https://linkup-vibe.s3.eu-central-1.amazonaws.com/ads/restaurant5.jpg',
        ];
        $restaurantVideos = [
            'https://linkup-vibe.s3.eu-central-1.amazonaws.com/ads/restaurant2.mp4',
            'https://linkup-vibe.s3.eu-central-1.amazonaws.com/ads/restaurant5.mp4',
        ];
        $restaurantThumbnails = [
            'https://linkup-vibe.s3.eu-central-1.amazonaws.com/ads/restaurant2_thumb.jpg',
            'https://linkup-vibe.s3.eu-central-1.amazonaws.com/ads/restaurant5_thumb.jpg',
        ];

        $clubImages = [
            'https://linkup-vibe.s3.eu-central-1.amazonaws.com/ads/club1.jpg',
            'https://linkup-vibe.s3.eu-central-1.amazonaws.com/ads/club2.jpg',
            'https://linkup-vibe.s3.eu-central-1.amazonaws.com/ads/club3.jpg',
            'https://linkup-vibe.s3.eu-central-1.amazonaws.com/ads/club4.jpg',
            'https://linkup-vibe.s3.eu-central-1.amazonaws.com/ads/club5.jpg',
        ];
        $clubVideos = [
            'https://linkup-vibe.s3.eu-central-1.amazonaws.com/ads/club1.mp4',
            'https://linkup-vibe.s3.eu-central-1.amazonaws.com/ads/club3.mp4',
            'https://linkup-vibe.s3.eu-central-1.amazonaws.com/ads/club5.mp4',
        ];
        $clubThumbnails = [
            'https://linkup-vibe.s3.eu-central-1.amazonaws.com/ads/club1_thumb.jpg',
            'https://linkup-vibe.s3.eu-central-1.amazonaws.com/ads/club3_thumb.jpg',
            'https://linkup-vibe.s3.eu-central-1.amazonaws.com/ads/club5_thumb.jpg',
        ];

        $generalImages = [
            'https://linkup-vibe.s3.eu-central-1.amazonaws.com/ads/general1.jpg',
            'https://linkup-vibe.s3.eu-central-1.amazonaws.com/ads/general2.jpg',
            'https://linkup-vibe.s3.eu-central-1.amazonaws.com/ads/general3.jpg',
            'https://linkup-vibe.s3.eu-central-1.amazonaws.com/ads/general4.jpg',
            'https://linkup-vibe.s3.eu-central-1.amazonaws.com/ads/general5.jpg',
        ];
        $generalVideos = [
            'https://linkup-vibe.s3.eu-central-1.amazonaws.com/ads/general2.mp4',
            'https://linkup-vibe.s3.eu-central-1.amazonaws.com/ads/general5.mp4',
        ];
        $generalThumbnails = [
            'https://linkup-vibe.s3.eu-central-1.amazonaws.com/ads/general2_thumb.jpg',
            'https://linkup-vibe.s3.eu-central-1.amazonaws.com/ads/general5_thumb.jpg',
        ];

        // Restaurant Ads (5)
        $restaurantAds = [
            [
                'name' => 'Tony\'s Pizzeria',
                'headline' => 'Best Pizza in Downtown Miami',
                'description' => 'Authentic Italian pizza made with fresh ingredients and family recipes since 1985.',
                'category' => 'restaurant',
                'country' => 'USA',
                'state' => 'Florida',
                'city' => 'Miami',
                'location' => 'Downtown Miami',
                'email' => 'tony@tonyspizzeria.com',
                'phone' => '3055550123',
                'www' => 'https://tonyspizzeria.com',
                'ad_type' => 'image',
                'image' => $restaurantImages[0],
                'video' => null,
                'thumbnail' => null,
                'max_duration' => 15,
                'autoplay_sound' => 'off',
                'cta_overlay_timing' => 'end',
                'loop_video' => 'yes',
                'cta_text' => 'Order Now',
                'brand_color' => '#FF6B35',
                'cost' => 749,
                'paid' => 'growth',
                'is_paid' => true,
                'status' => '1',
                'start_date' => $startDate,
                'end_date' => $endDate,
                'duration_days' => 30,
                'price_package' => 'growth',
                'publication_status' => 'Active',
                'targeting_notes' => 'Target foodies aged 21-35 in Miami area',
            ],
            [
                'name' => 'Sushi Zen',
                'headline' => 'Fresh Sushi Daily',
                'description' => 'Premium sushi bar with daily fresh fish imports and omakase experience.',
                'category' => 'restaurant',
                'country' => 'USA',
                'state' => 'California',
                'city' => 'Los Angeles',
                'location' => 'West Hollywood',
                'email' => 'info@sushizen.com',
                'phone' => '3105550456',
                'www' => 'https://sushizen.com',
                'ad_type' => 'video',
                'image' => $restaurantImages[1],
                'video' => $restaurantVideos[0],
                'thumbnail' => $restaurantThumbnails[0],
                'max_duration' => 10,
                'autoplay_sound' => 'muted',
                'cta_overlay_timing' => 'after_5s',
                'loop_video' => 'no',
                'cta_text' => 'Reserve Table',
                'brand_color' => '#2E8B57',
                'cost' => 1999,
                'paid' => 'network',
                'is_paid' => true,
                'status' => '1',
                'start_date' => $startDate,
                'end_date' => $endDate,
                'duration_days' => 30,
                'price_package' => 'network',
                'publication_status' => 'Active',
                'targeting_notes' => 'High-income professionals in LA',
            ],
            [
                'name' => 'Burger Palace',
                'headline' => 'Gourmet Burgers & Craft Beer',
                'description' => 'Hand-crafted burgers with locally sourced beef and extensive craft beer selection.',
                'category' => 'restaurant',
                'country' => 'USA',
                'state' => 'Texas',
                'city' => 'Austin',
                'location' => 'South Austin',
                'email' => 'hello@burgerpalace.com',
                'phone' => '5125550789',
                'www' => 'https://burgerpalace.com',
                'ad_type' => 'image',
                'image' => $restaurantImages[2],
                'video' => null,
                'thumbnail' => null,
                'max_duration' => 15,
                'autoplay_sound' => 'off',
                'cta_overlay_timing' => 'immediate',
                'loop_video' => 'yes',
                'cta_text' => 'View Menu',
                'brand_color' => '#E74C3C',
                'cost' => 249,
                'paid' => 'starter',
                'is_paid' => true,
                'status' => '1',
                'start_date' => $startDate,
                'end_date' => $endDate,
                'duration_days' => 30,
                'price_package' => 'starter',
                'publication_status' => 'Active',
                'targeting_notes' => 'Young adults and families in Austin',
            ],
            [
                'name' => 'La Cocina Mexicana',
                'headline' => 'Authentic Mexican Cuisine',
                'description' => 'Family-owned restaurant serving traditional Mexican dishes made with recipes passed down for generations.',
                'category' => 'restaurant',
                'country' => 'USA',
                'state' => 'Arizona',
                'city' => 'Phoenix',
                'location' => 'Central Phoenix',
                'email' => 'info@lacocina.com',
                'phone' => '6025550321',
                'www' => 'https://lacocina.com',
                'ad_type' => 'image',
                'image' => $restaurantImages[3],
                'video' => null,
                'thumbnail' => null,
                'max_duration' => 15,
                'autoplay_sound' => 'off',
                'cta_overlay_timing' => 'end',
                'loop_video' => 'yes',
                'cta_text' => 'Order Delivery',
                'brand_color' => '#F39C12',
                'cost' => 749,
                'paid' => 'growth',
                'is_paid' => true,
                'status' => '1',
                'start_date' => $startDate,
                'end_date' => $endDate,
                'duration_days' => 30,
                'price_package' => 'growth',
                'publication_status' => 'Active',
                'targeting_notes' => 'Mexican food lovers in Phoenix metro',
            ],
            [
                'name' => 'The Steakhouse',
                'headline' => 'Premium Steaks & Fine Dining',
                'description' => 'Upscale steakhouse with USDA Prime beef, extensive wine list, and elegant atmosphere.',
                'category' => 'restaurant',
                'country' => 'USA',
                'state' => 'New York',
                'city' => 'New York City',
                'location' => 'Manhattan',
                'email' => 'reservations@thesteakhouse.com',
                'phone' => '2125550654',
                'www' => 'https://thesteakhouse.com',
                'ad_type' => 'video',
                'image' => $restaurantImages[4],
                'video' => $restaurantVideos[1],
                'thumbnail' => $restaurantThumbnails[1],
                'max_duration' => 20,
                'autoplay_sound' => 'muted',
                'cta_overlay_timing' => 'after_10s',
                'loop_video' => 'no',
                'cta_text' => 'Book Now',
                'brand_color' => '#8B0000',
                'cost' => 1999,
                'paid' => 'network',
                'is_paid' => true,
                'status' => '1',
                'start_date' => $startDate,
                'end_date' => $endDate,
                'duration_days' => 30,
                'price_package' => 'network',
                'publication_status' => 'Active',
                'targeting_notes' => 'Affluent professionals in NYC',
            ],
        ];

        // Club/Fête Ads (5)
        $clubAds = [
            [
                'name' => 'Neon Nights Club',
                'headline' => 'Dance Until Dawn',
                'description' => 'Premier nightclub with top DJs, VIP bottle service, and electric atmosphere every weekend.',
                'category' => 'club',
                'country' => 'USA',
                'state' => 'Nevada',
                'city' => 'Las Vegas',
                'location' => 'The Strip',
                'email' => 'info@neonnights.com',
                'phone' => '7025550987',
                'www' => 'https://neonnights.com',
                'ad_type' => 'video',
                'image' => $clubImages[0],
                'video' => $clubVideos[0],
                'thumbnail' => $clubThumbnails[0],
                'max_duration' => 15,
                'autoplay_sound' => 'on',
                'cta_overlay_timing' => 'end',
                'loop_video' => 'yes',
                'cta_text' => 'Get Tickets',
                'brand_color' => '#9B59B6',
                'cost' => 1999,
                'paid' => 'network',
                'is_paid' => true,
                'status' => '1',
                'start_date' => $startDate,
                'end_date' => $endDate,
                'duration_days' => 30,
                'price_package' => 'network',
                'publication_status' => 'Active',
                'targeting_notes' => 'Party-goers aged 21-35 visiting Vegas',
            ],
            [
                'name' => 'Rooftop Lounge',
                'headline' => 'Skyline Views & Cocktails',
                'description' => 'Exclusive rooftop bar with panoramic city views, craft cocktails, and live music.',
                'category' => 'club',
                'country' => 'USA',
                'state' => 'Illinois',
                'city' => 'Chicago',
                'location' => 'River North',
                'email' => 'vip@rooftoplounge.com',
                'phone' => '3125550135',
                'www' => 'https://rooftoplounge.com',
                'ad_type' => 'image',
                'image' => $clubImages[1],
                'video' => null,
                'thumbnail' => null,
                'max_duration' => 15,
                'autoplay_sound' => 'off',
                'cta_overlay_timing' => 'immediate',
                'loop_video' => 'yes',
                'cta_text' => 'Reserve VIP',
                'brand_color' => '#1ABC9C',
                'cost' => 749,
                'paid' => 'growth',
                'is_paid' => true,
                'status' => '1',
                'start_date' => $startDate,
                'end_date' => $endDate,
                'duration_days' => 30,
                'price_package' => 'growth',
                'publication_status' => 'Active',
                'targeting_notes' => 'Young professionals in Chicago',
            ],
            [
                'name' => 'Beach Party Festival',
                'headline' => 'Summer Beach Bash 2024',
                'description' => 'Annual beach festival with live bands, DJs, food trucks, and sunset parties.',
                'category' => 'club',
                'country' => 'USA',
                'state' => 'Florida',
                'city' => 'Miami Beach',
                'location' => 'South Beach',
                'email' => 'tickets@beachparty.com',
                'phone' => '3055550246',
                'www' => 'https://beachparty.com',
                'ad_type' => 'video',
                'image' => $clubImages[2],
                'video' => $clubVideos[1],
                'thumbnail' => $clubThumbnails[1],
                'max_duration' => 10,
                'autoplay_sound' => 'muted',
                'cta_overlay_timing' => 'after_5s',
                'loop_video' => 'no',
                'cta_text' => 'Buy Passes',
                'brand_color' => '#00CED1',
                'cost' => 1999,
                'paid' => 'network',
                'is_paid' => true,
                'status' => '1',
                'start_date' => $startDate,
                'end_date' => $endDate,
                'duration_days' => 30,
                'price_package' => 'network',
                'publication_status' => 'Active',
                'targeting_notes' => 'Festival-goers and beach lovers',
            ],
            [
                'name' => 'Underground Jazz',
                'headline' => 'Live Jazz Every Night',
                'description' => 'Intimate jazz club featuring local and national artists in a speakeasy-style setting.',
                'category' => 'club',
                'country' => 'USA',
                'state' => 'Louisiana',
                'city' => 'New Orleans',
                'location' => 'French Quarter',
                'email' => 'bookings@undergroundjazz.com',
                'phone' => '5045550579',
                'www' => 'https://undergroundjazz.com',
                'ad_type' => 'image',
                'image' => $clubImages[3],
                'video' => null,
                'thumbnail' => null,
                'max_duration' => 15,
                'autoplay_sound' => 'off',
                'cta_overlay_timing' => 'end',
                'loop_video' => 'yes',
                'cta_text' => 'See Schedule',
                'brand_color' => '#D35400',
                'cost' => 249,
                'paid' => 'starter',
                'is_paid' => true,
                'status' => '1',
                'start_date' => $startDate,
                'end_date' => $endDate,
                'duration_days' => 30,
                'price_package' => 'starter',
                'publication_status' => 'Active',
                'targeting_notes' => 'Jazz enthusiasts and music lovers',
            ],
            [
                'name' => 'Electric Carnival',
                'headline' => 'EDM Night Experience',
                'description' => 'High-energy electronic dance music venue with world-class DJs and immersive light shows.',
                'category' => 'club',
                'country' => 'USA',
                'state' => 'California',
                'city' => 'San Francisco',
                'location' => 'SOMA District',
                'email' => 'info@electriccarnival.com',
                'phone' => '4155550802',
                'www' => 'https://electriccarnival.com',
                'ad_type' => 'video',
                'image' => $clubImages[4],
                'video' => $clubVideos[2],
                'thumbnail' => $clubThumbnails[2],
                'max_duration' => 15,
                'autoplay_sound' => 'on',
                'cta_overlay_timing' => 'after_10s',
                'loop_video' => 'yes',
                'cta_text' => 'Get VIP Access',
                'brand_color' => '#FF1493',
                'cost' => 1999,
                'paid' => 'network',
                'is_paid' => true,
                'status' => '1',
                'start_date' => $startDate,
                'end_date' => $endDate,
                'duration_days' => 30,
                'price_package' => 'network',
                'publication_status' => 'Active',
                'targeting_notes' => 'EDM fans and party enthusiasts',
            ],
        ];

        // General Ads (5)
        $generalAds = [
            [
                'name' => 'FitLife Gym',
                'headline' => 'Transform Your Body',
                'description' => 'State-of-the-art fitness center with personal trainers, group classes, and 24/7 access.',
                'category' => 'general',
                'country' => 'USA',
                'state' => 'Colorado',
                'city' => 'Denver',
                'location' => 'Downtown Denver',
                'email' => 'join@fitlifegym.com',
                'phone' => '3035550191',
                'www' => 'https://fitlifegym.com',
                'ad_type' => 'image',
                'image' => $generalImages[0],
                'video' => null,
                'thumbnail' => null,
                'max_duration' => 15,
                'autoplay_sound' => 'off',
                'cta_overlay_timing' => 'immediate',
                'loop_video' => 'yes',
                'cta_text' => 'Start Free Trial',
                'brand_color' => '#27AE60',
                'cost' => 749,
                'paid' => 'growth',
                'is_paid' => true,
                'status' => '1',
                'start_date' => $startDate,
                'end_date' => $endDate,
                'duration_days' => 30,
                'price_package' => 'growth',
                'publication_status' => 'Active',
                'targeting_notes' => 'Fitness enthusiasts aged 18-45',
            ],
            [
                'name' => 'TechStore Pro',
                'headline' => 'Latest Gadgets & Electronics',
                'description' => 'Your one-stop shop for the newest smartphones, laptops, and tech accessories.',
                'category' => 'general',
                'country' => 'USA',
                'state' => 'Washington',
                'city' => 'Seattle',
                'location' => 'Bellevue',
                'email' => 'sales@techstorepro.com',
                'phone' => '2065550357',
                'www' => 'https://techstorepro.com',
                'ad_type' => 'video',
                'image' => $generalImages[1],
                'video' => $generalVideos[0],
                'thumbnail' => $generalThumbnails[0],
                'max_duration' => 10,
                'autoplay_sound' => 'muted',
                'cta_overlay_timing' => 'after_5s',
                'loop_video' => 'no',
                'cta_text' => 'Shop Now',
                'brand_color' => '#3498DB',
                'cost' => 749,
                'paid' => 'growth',
                'is_paid' => true,
                'status' => '1',
                'start_date' => $startDate,
                'end_date' => $endDate,
                'duration_days' => 30,
                'price_package' => 'growth',
                'publication_status' => 'Active',
                'targeting_notes' => 'Tech-savvy consumers',
            ],
            [
                'name' => 'Travel Adventures',
                'headline' => 'Explore The World',
                'description' => 'Curated travel experiences and adventure packages to destinations worldwide.',
                'category' => 'general',
                'country' => 'USA',
                'state' => 'New York',
                'city' => 'New York City',
                'location' => 'Manhattan',
                'email' => 'book@traveladventures.com',
                'phone' => '2125550468',
                'www' => 'https://traveladventures.com',
                'ad_type' => 'image',
                'image' => $generalImages[2],
                'video' => null,
                'thumbnail' => null,
                'max_duration' => 15,
                'autoplay_sound' => 'off',
                'cta_overlay_timing' => 'end',
                'loop_video' => 'yes',
                'cta_text' => 'Plan Your Trip',
                'brand_color' => '#E67E22',
                'cost' => 1999,
                'paid' => 'network',
                'is_paid' => true,
                'status' => '1',
                'start_date' => $startDate,
                'end_date' => $endDate,
                'duration_days' => 30,
                'price_package' => 'network',
                'publication_status' => 'Active',
                'targeting_notes' => 'Travel enthusiasts and adventure seekers',
            ],
            [
                'name' => 'Beauty Bliss Spa',
                'headline' => 'Relax & Rejuvenate',
                'description' => 'Luxury day spa offering massages, facials, and wellness treatments in a serene environment.',
                'category' => 'general',
                'country' => 'USA',
                'state' => 'California',
                'city' => 'Los Angeles',
                'location' => 'Beverly Hills',
                'email' => 'appointments@beautybliss.com',
                'phone' => '3105550579',
                'www' => 'https://beautybliss.com',
                'ad_type' => 'image',
                'image' => $generalImages[3],
                'video' => null,
                'thumbnail' => null,
                'max_duration' => 15,
                'autoplay_sound' => 'off',
                'cta_overlay_timing' => 'immediate',
                'loop_video' => 'yes',
                'cta_text' => 'Book Appointment',
                'brand_color' => '#F8BBD9',
                'cost' => 249,
                'paid' => 'starter',
                'is_paid' => true,
                'status' => '1',
                'start_date' => $startDate,
                'end_date' => $endDate,
                'duration_days' => 30,
                'price_package' => 'starter',
                'publication_status' => 'Active',
                'targeting_notes' => 'Women aged 25-55 in LA area',
            ],
            [
                'name' => 'AutoElite Dealership',
                'headline' => 'Premium Pre-Owned Vehicles',
                'description' => 'Certified pre-owned luxury cars with warranty, financing options, and exceptional service.',
                'category' => 'general',
                'country' => 'USA',
                'state' => 'Texas',
                'city' => 'Houston',
                'location' => 'Galleria Area',
                'email' => 'sales@autoelite.com',
                'phone' => '7135550691',
                'www' => 'https://autoelite.com',
                'ad_type' => 'video',
                'image' => $generalImages[4],
                'video' => $generalVideos[1],
                'thumbnail' => $generalThumbnails[1],
                'max_duration' => 15,
                'autoplay_sound' => 'muted',
                'cta_overlay_timing' => 'after_10s',
                'loop_video' => 'no',
                'cta_text' => 'View Inventory',
                'brand_color' => '#2C3E50',
                'cost' => 749,
                'paid' => 'growth',
                'is_paid' => true,
                'status' => '1',
                'start_date' => $startDate,
                'end_date' => $endDate,
                'duration_days' => 30,
                'price_package' => 'growth',
                'publication_status' => 'Active',
                'targeting_notes' => 'Car buyers looking for luxury vehicles',
            ],
        ];

        // Merge all ads
        $allAds = array_merge($restaurantAds, $clubAds, $generalAds);

        // Insert ads
        foreach ($allAds as $ad) {
            Advertisement::updateOrCreate(
                ['name' => $ad['name'], 'headline' => $ad['headline']],
                $ad
            );
        }

        $this->command->info('Successfully seeded 15 advertisements (5 restaurant, 5 club, 5 general).');
    }
}
